remote_theme: daviddarnes/alembic@master
plugins: 
-jekyll-remote-theme

title: Snake-Recognizer
description: An image classifier model that classifies 18 different types of venomous snakes.

author:
  name: A B M RAGIB HASAN
